version: '2'
services:
  app:
    build: .
    ports:
    - 80:3000/tcp
    command:
    - bundle
    - exec
    - rails
    - s
    - -p
    - '3000'
    - -b
    - 0.0.0.0
    volumes:
      - ./raspberry-app:/app
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: raspberry 
      POSTGRES_USER: raspberry_user
  eventserver:
    image: python:3.5
    volumes:
      - ./event-server:/event-server
    command: 
      - python3
      - /event-server/server.py
    ports:
      - 6500:6500
