version: '2'
services:
  app:
    build: ./raspberry-app
    ports:
    - 80:3000/tcp
    command:
    - bundle
    - exec
    - rails
    - s
    - -p
    - '3000'
    - -b
    - 0.0.0.0
    volumes:
      - ./raspberry-app:/app
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: raspberry 
      POSTGRES_USER: raspberry_user
  eventserver:
    build: ./event-server
    volumes:
    - ./event-server:/event-server
    ports:
    - 6500:6500
